const API_URL = 'https://script.google.com/macros/s/AKfycbwpxg2E5B4u55MtE_zjziRcf5V-ei887yMwuro4HhvXcEh5R_KIGJqvNjXkqDBvMKSkRQ/exec';
const $ = id => document.getElementById(id);
const money = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const today = new Date().toISOString().slice(0,10); let state={user:null,token:null,transactions:[],budgets:[],savings:[]}; let charts={};
function localMode(){return API_URL.includes('PASTE_');}
async function api(action, payload={}){ if(localMode()) return mockApi(action,payload); const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:state.token,...payload})}); const data=await res.json(); if(!data.ok) throw new Error(data.message||'Terjadi kesalahan'); return data; }
function mockApi(action,p){ const demo=JSON.parse(localStorage.getItem('off_demo')||'{"transactions":[],"budgets":[],"savings":[]}'); if(action==='login') return Promise.resolve(p.username==='admin'&&p.password==='ongsfamily123'?{ok:true,token:'demo',user:{name:'Ongs Family',role:'admin'}}:{ok:false,message:'Login salah'}); if(action==='getAll') return Promise.resolve({ok:true,...demo}); if(action==='saveTransaction'){p.data.id=p.data.id||'TX'+Date.now(); demo.transactions=demo.transactions.filter(x=>x.id!==p.data.id).concat(p.data); localStorage.setItem('off_demo',JSON.stringify(demo)); return Promise.resolve({ok:true});} if(action==='deleteTransaction'){demo.transactions=demo.transactions.filter(x=>x.id!==p.id); localStorage.setItem('off_demo',JSON.stringify(demo)); return Promise.resolve({ok:true});} if(action==='saveBudget'){p.data.id='B'+Date.now(); demo.budgets=demo.budgets.filter(x=>!(x.month===p.data.month&&x.category===p.data.category)).concat(p.data); localStorage.setItem('off_demo',JSON.stringify(demo)); return Promise.resolve({ok:true});} if(action==='saveSaving'){p.data.id=p.data.id||'S'+Date.now(); demo.savings=demo.savings.filter(x=>x.id!==p.data.id).concat(p.data); localStorage.setItem('off_demo',JSON.stringify(demo)); return Promise.resolve({ok:true});} if(action==='deleteSaving'){demo.savings=demo.savings.filter(x=>x.id!==p.id); localStorage.setItem('off_demo',JSON.stringify(demo)); return Promise.resolve({ok:true});} }
$('todayLabel').textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',year:'numeric',month:'long',day:'numeric'}); $('txDate').value=today; $('filterMonth').value=today.slice(0,7); $('budgetMonth').value=today.slice(0,7); $('savingDeadline').value=new Date(new Date().setFullYear(new Date().getFullYear()+1)).toISOString().slice(0,10);
$('loginForm').onsubmit=async e=>{e.preventDefault(); $('loginMsg').textContent='Memproses...'; try{const d=await api('login',{username:$('username').value,password:$('password').value}); if(!d.ok) throw new Error(d.message); state.user=d.user; state.token=d.token; $('loginPage').classList.add('hidden'); $('appPage').classList.remove('hidden'); $('userLabel').textContent=d.user.name+' · '+d.user.role; await loadAll();}catch(err){$('loginMsg').textContent=err.message;}};
$('logoutBtn').onclick=()=>location.reload(); document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active')); b.classList.add('active'); document.querySelectorAll('.page').forEach(x=>x.classList.remove('show')); $(b.dataset.page).classList.add('show'); $('pageTitle').textContent=b.textContent; renderAll();});
async function loadAll(){const d=await api('getAll'); state.transactions=d.transactions||[]; state.budgets=d.budgets||[]; state.savings=d.savings||[]; renderAll();}
function calc(){const inc=state.transactions.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0), exp=state.transactions.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0); const save=state.savings.reduce((s,x)=>s+Number(x.current),0); const expenseRatio=inc?exp/inc:0, savingRatio=inc?save/inc:0; let score=Math.max(0,Math.min(100,Math.round((expenseRatio<.7?35:expenseRatio<.9?20:5)+(savingRatio>.3?35:savingRatio>.15?25:10)+(state.savings.length?15:5)+(state.budgets.length?15:5)))); return {inc,exp,balance:inc-exp,save,expenseRatio,savingRatio,score,status:score>=80?'Sangat Sehat':score>=65?'Baik':score>=50?'Waspada':'Bahaya'};}
function renderAll(){renderDashboard(); renderTransactions(); renderBudgets(); renderSavings(); renderReport();}
function renderDashboard(){const c=calc(); $('kpiIncome').textContent=money(c.inc); $('kpiExpense').textContent=money(c.exp); $('kpiBalance').textContent=money(c.balance); $('kpiScore').textContent=c.score+'/100'; $('kpiStatus').textContent=c.status; renderSavingProgress(); renderInsights(c); renderCharts();}
function groupMonth(){let m={}; state.transactions.forEach(x=>{let k=(x.date||'').slice(0,7); if(!m[k])m[k]={income:0,expense:0}; m[k][x.type]+=Number(x.amount)}); return Object.entries(m).sort();}
function renderCharts(){const gm=groupMonth(), labels=gm.map(x=>x[0]), income=gm.map(x=>x[1].income), expense=gm.map(x=>x[1].expense); if(charts.cash) charts.cash.destroy(); charts.cash=new Chart($('cashflowChart'),{type:'bar',data:{labels,datasets:[{label:'Pemasukan',data:income},{label:'Pengeluaran',data:expense}]},options:{responsive:true}}); let cats={}; state.transactions.filter(x=>x.type==='expense').forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount)); if(charts.cat) charts.cat.destroy(); charts.cat=new Chart($('categoryChart'),{type:'doughnut',data:{labels:Object.keys(cats),datasets:[{data:Object.values(cats)}]},options:{responsive:true}});}
function renderSavingProgress(){ $('savingProgress').innerHTML= state.savings.length? state.savings.map(s=>{let p=Math.min(100,Math.round(Number(s.current)/Number(s.target)*100||0)); return `<p><b>${s.name}</b> <span>${money(s.current)} / ${money(s.target)} (${p}%)</span></p><div class="progress"><div class="bar" style="width:${p}%"></div></div>`}).join(''):'<p>Belum ada target tabungan.</p>'; }
function renderInsights(c){let wants=state.transactions.filter(x=>x.priority==='Keinginan').reduce((s,x)=>s+Number(x.amount),0); const arr=[`Status keuangan keluarga: <b>${c.status}</b> dengan skor ${c.score}/100.`,`Rasio pengeluaran: <b>${Math.round(c.expenseRatio*100)}%</b> dari pemasukan.`,`Rasio tabungan tercatat: <b>${Math.round(c.savingRatio*100)}%</b> dari pemasukan.`, wants>0?`Pengeluaran keinginan: <b>${money(wants)}</b>. Evaluasi jika lebih dari 20% pemasukan.`:`Pengeluaran keinginan belum tercatat.`]; $('insights').innerHTML=arr.map(x=>`<li>${x}</li>`).join('');}
document.querySelectorAll('.quick-buttons button').forEach(b=>b.onclick=()=>{$('txType').value=b.dataset.type; $('txCategory').value=b.dataset.category; $('txPriority').value=b.dataset.priority; $('txAmount').focus();});
$('txForm').onsubmit=async e=>{e.preventDefault(); const data={id:$('txId').value,date:$('txDate').value,type:$('txType').value,category:$('txCategory').value,account:$('txAccount').value,priority:$('txPriority').value,amount:Number($('txAmount').value),note:$('txNote').value}; await api('saveTransaction',{data}); $('txMsg').textContent='Transaksi berhasil disimpan.'; e.target.reset(); $('txDate').value=today; $('txId').value=''; await loadAll();}; $('resetForm').onclick=()=>{$('txForm').reset();$('txDate').value=today;$('txId').value='';};
function renderTransactions(){const q=($('searchBox').value||'').toLowerCase(), ft=$('filterType').value, fm=$('filterMonth').value; const rows=state.transactions.filter(x=>(ft==='all'||x.type===ft)&&(!fm||(x.date||'').startsWith(fm))&&((x.category+x.note).toLowerCase().includes(q))).sort((a,b)=>(b.date||'').localeCompare(a.date||'')); $('txTable').innerHTML=rows.map(x=>`<tr><td>${x.date}</td><td class="${x.type}">${x.type==='income'?'Pemasukan':'Pengeluaran'}</td><td>${x.category}</td><td>${x.account}</td><td>${x.priority}</td><td>${money(x.amount)}</td><td>${x.note||''}</td><td><button onclick="editTx('${x.id}')">Edit</button> <button class="secondary" onclick="delTx('${x.id}')">Hapus</button></td></tr>`).join('');}
$('searchBox').oninput=$('filterType').onchange=$('filterMonth').onchange=renderTransactions; window.editTx=id=>{let x=state.transactions.find(a=>a.id===id); if(!x)return; ['Id','Date','Type','Category','Account','Priority','Amount','Note'].forEach(k=>{$('tx'+k).value=x[k.toLowerCase()]||''}); document.querySelector('[data-page="quick"]').click();}; window.delTx=async id=>{if(confirm('Hapus transaksi ini?')){await api('deleteTransaction',{id}); await loadAll();}};
$('budgetForm').onsubmit=async e=>{e.preventDefault(); await api('saveBudget',{data:{month:$('budgetMonth').value,category:$('budgetCategory').value,limit:Number($('budgetLimit').value)}}); e.target.reset(); $('budgetMonth').value=today.slice(0,7); await loadAll();};
function renderBudgets(){ $('budgetTable').innerHTML=state.budgets.map(b=>{let used=state.transactions.filter(x=>x.type==='expense'&&(x.date||'').startsWith(b.month)&&x.category===b.category).reduce((s,x)=>s+Number(x.amount),0), p=Number(b.limit)?used/Number(b.limit):0, cls=p>1?'bad':p>.8?'warn':'ok'; return `<tr><td>${b.month}</td><td>${b.category}</td><td>${money(b.limit)}</td><td>${money(used)}</td><td><span class="tag ${cls}">${p>1?'Melebihi':p>.8?'Hampir Habis':'Aman'}</span></td></tr>`}).join('');}
$('savingForm').onsubmit=async e=>{e.preventDefault(); await api('saveSaving',{data:{name:$('savingName').value,target:Number($('savingTarget').value),current:Number($('savingCurrent').value),deadline:$('savingDeadline').value}}); e.target.reset(); await loadAll();};
function renderSavings(){ $('savingTable').innerHTML=state.savings.map(s=>{let p=Math.min(100,Math.round(Number(s.current)/Number(s.target)*100||0)); return `<tr><td>${s.name}</td><td>${money(s.target)}</td><td>${money(s.current)}</td><td><div class="progress"><div class="bar" style="width:${p}%"></div></div> ${p}%</td><td>${s.deadline}</td><td><button class="secondary" onclick="delSaving('${s.id}')">Hapus</button></td></tr>`}).join('');} window.delSaving=async id=>{if(confirm('Hapus target?')){await api('deleteSaving',{id}); await loadAll();}};
function renderReport(){const c=calc(); $('reportBox').innerHTML=[['Total Pemasukan',money(c.inc)],['Total Pengeluaran',money(c.exp)],['Saldo Bersih',money(c.balance)],['Financial Health Score',c.score+'/100 - '+c.status],['Rasio Pengeluaran',Math.round(c.expenseRatio*100)+'%'],['Rasio Tabungan',Math.round(c.savingRatio*100)+'%'],['Rekomendasi Auditor',c.expenseRatio>.9?'Tekan pengeluaran dan evaluasi kategori keinginan.':c.savingRatio<.1?'Naikkan porsi tabungan minimal 10–20%.':'Cashflow keluarga relatif sehat. Pertahankan disiplin budget.']].map(x=>`<div class="report-item"><span>${x[0]}</span><h3>${x[1]}</h3></div>`).join('');}
